[general]

library_name = "WiringPi"
output_file_path = "src/WiringPi.jl"
module_name = "WiringPi"
jll_pkg_name = "WiringPi_jll"
use_deterministic_symbol = true
export_symbol_prefixes = []
use_julia_native_enum_type = true
smart_de_anonymize = true
extract_c_comment_style = "raw"
show_c_function_prototype = false

always_NUL_terminated_string = true



add_comment_for_skipped_macro = true

[codegen]
is_function_strictly_typed = true
opaque_as_mutable_struct = true
wrap_variadic_function = true
use_julia_bool = true